version: 0.0
os: linux
files:
  - source: /app.js
    destination: /home/ec2-user/node-website
  - source: /package.json
    destination: /home/ec2-user/node-website
  - source: /public/
    destination: /home/ec2-user/node-website/public
hooks:
  ApplicationStop:
     - location: Scripts/deregister_from_elb.sh
       timeout: 180
  ApplicationStart:
     - location: Scripts/register_with_elb.sh
       timeout: 180
